services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./packages:/app/packages
      - /app/node_modules
      - /app/app/web/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - challenge-network
    command: npm run dev -- --host 0.0.0.0
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - ./packages:/app/packages
      - /app/node_modules
      - /app/app/api-gateway/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AUTH_SERVICE_URL=tcp://auth-service:3002
      - TASKS_SERVICE_URL=tcp://tasks-service:3004
      - NOTIFS_SERVICE_URL=tcp://notifications-service:3003
      - USER_SERVICE_URL=tcp://user-service:3005
      - JWT_SECRET=supersecret
      - JWT_REFRESH_SECRET=superrefresh
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network

  # Auth Service
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
      target: development
    ports:
      - '3002:3002'
      - '3007:3007'
    volumes:
      - .:/app
      - ./packages:/app/packages
      - /app/node_modules
      - /app/app/auth-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgres://admin:admin@db:5432/task-manager-jungle
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=task-manager-jungle
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - JWT_SECRET=supersecret
      - JWT_REFRESH_SECRET=superrefresh
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network

  # Tasks Service
  tasks-service:
    container_name: tasks-service
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
      target: development
    ports:
      - '3004:3004'
      - '3008:3008'
    volumes:
      - .:/app
      - ./packages:/app/packages
      - /app/node_modules
      - /app/app/tasks-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MICROSERVICE_PORT=3004
      - DATABASE_URL=postgres://admin:admin@db:5432/task-manager-jungle
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=task-manager-jungle
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network

  # Notifications Service
  notifications-service:
    container_name: notifications-service
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
      target: development
    ports:
      - '3003:3003'
      - '3006:3006'
    volumes:
      - .:/app
      - ./packages:/app/packages
      - /app/node_modules
      - /app/app/notifications-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DATABASE_URL=postgres://admin:admin@db:5432/task-manager-jungle
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=task-manager-jungle
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - WS_PORT=3004
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network
  # Notifications Service
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
      target: development
    ports:
      - '3005:3005'
    volumes:
      - .:/app
      - ./packages:/app/packages
      - /app/node_modules
      - /app/app/user-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DATABASE_URL=postgres://admin:admin@db:5432/task-manager-jungle
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=task-manager-jungle
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network

  # Postgres Database
  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    ports:
      - '5435:5432'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: task-manager-jungle
    networks:
      - challenge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d task-manager-jungle"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - challenge-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  challenge-network:
    driver: bridge
